name: defendher
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Main dependencies for your app
  geolocator: ^10.1.0
  vibration: ^1.7.4


  # If you want to remove audioplayers (since you said to remove audio), you can delete this line:
  # audioplayers: ^3.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assests/sos_alarm.mp3
    - assests/logo.png
